# Uncomment the next line to define a global platform for your project
platform :ios, "11.0"

target 'DNSDemo' do

  pod "AFNetworking" 
  pod "MSDKHttpDNS", :path => "local_pods/MSDKHttpDNS"
#  pod 'MSDKDns_C11'
end
